// Code generated by MockGen. DO NOT EDIT.
// Source: routes.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/kgoralski/go-crud-template/internal/banks/domain"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetBanks mocks base method
func (m *MockService) GetBanks() ([]domain.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBanks")
	ret0, _ := ret[0].([]domain.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBanks indicates an expected call of GetBanks
func (mr *MockServiceMockRecorder) GetBanks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBanks", reflect.TypeOf((*MockService)(nil).GetBanks))
}

// GetBank mocks base method
func (m *MockService) GetBank(id int) (*domain.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBank", id)
	ret0, _ := ret[0].(*domain.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBank indicates an expected call of GetBank
func (mr *MockServiceMockRecorder) GetBank(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBank", reflect.TypeOf((*MockService)(nil).GetBank), id)
}

// Create mocks base method
func (m *MockService) Create(bank domain.Bank) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", bank)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockServiceMockRecorder) Create(bank interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), bank)
}

// DeleteBanks mocks base method
func (m *MockService) DeleteBanks() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBanks")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBanks indicates an expected call of DeleteBanks
func (mr *MockServiceMockRecorder) DeleteBanks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBanks", reflect.TypeOf((*MockService)(nil).DeleteBanks))
}

// Update mocks base method
func (m *MockService) Update(bank domain.Bank) (*domain.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", bank)
	ret0, _ := ret[0].(*domain.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockServiceMockRecorder) Update(bank interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), bank)
}

// Delete mocks base method
func (m *MockService) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), id)
}
