DROP DATABASE IF EXISTS bank_db;
CREATE DATABASE bank_db;

DROP USER IF EXISTS admin;
CREATE USER 'admin' IDENTIFIED BY 'Admin.123';
GRANT ALL PRIVILEGES ON bank_db.* TO 'admin';


DROP TABLE IF EXISTS bank_db.banks;
CREATE TABLE bank_db.banks (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;